{% set version = "3.2.3" %}

package:
  name: abismal
  version: {{ version }}

build:
  number: 0
  run_exports:
    # abismal is currently not intended to be stable between minor versions (x.x).
    - {{ pin_subpackage('abismal', max_pin="x.x") }}


source:
  url: https://github.com/smithlabcode/abismal/releases/download/v{{ version }}/abismal-{{ version }}.tar.gz
  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - zlib
    - htslib
  run:
    - zlib
    - htslib

about:
  home: https://github.com/smithlabcode/abismal
  license: GPL-3.0-only
  license_file: LICENSE
  summary: |
    abismal is a fast and memory-efficient mapper for short bisulfite sequencing reads
  doc_url: 'https://github.com/smithlabcode/abismal/blob/master/docs/MANUAL.md'

test:
  commands:
    - abismal

extra:
  recipe-maintainers:
    - andrewdavidsmith
    - guilhermesena1
